# Generated by Django 4.2.7 on 2023-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_alter_task_options_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_by',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
